### ISSUE TITLE
Height of terrain

### ISSUE THREAD

**Issue by PaweX** [tomsoftware/sied3#1]
The terrain is concave instead of convex. If you rotate screen by 180 degrees then it looks better:
![terrain_issue](https://cloud.githubusercontent.com/assets/3579486/14023804/711f7864-f1e6-11e5-9a38-ba05f1085f3b.jpg)

P.S. This project looks the most like S3 and I think it's good to continue it. (Terrain looks much better than in the JSettlers and it is written in C++). It may be good remake of S3 which may look like the original game.

**Comment by tomsoftware** [comment]
@PaweX Thanks. The development of this project has been stopped because the progress of the JSettlers is much more advanced (The map-read-function is copyed to the JSettlers Project and will be available in the next release - also some fixes in the terrain rendering). 

Now I'm focust on a Siedler 4 remake. So far I can read all resources and render the map. I will public this release soon.

**Comment by PaweX** [comment]
Settlers 4 - great! My favourite one. I was wondering if the BB studio would make the source code open (like Epsitec did with Colobot game).

**Comment by lstolcman** [comment]
@tomsoftware is it possible to share your settlers4 findings about file formats, resources etc?

**Comment by Platin21** [comment]
Still no progress at this point if you can give us a update on S4 would be great. 
Or if you need some help i definitely can program C++ and Dx11/OpenGL>3.0

**Comment by tomsoftware** [comment]
Hi, I set my current work on settlers 4 to public. See https://github.com/tomsoftware/Settlers.ts
